# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('blood_type', models.CharField(max_length=2)),
                ('allergies', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='physician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=40)),
                ('gender', models.CharField(max_length=40)),
                ('specialise', models.CharField(max_length=40)),
                ('date_of_birth', models.DateField()),
                ('address', models.TextField()),
            ],
        ),
    ]
